language: node_js
node_js:
  - "node"
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
  - develop
  - staging
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov yarn run unit

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coverage
notifications:
  email: true